//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/platform/libcore/ojluni/src/main/java/java/nio/file/ClosedFileSystemException.java
//

#include <JRE/J2ObjC_header.h>

#pragma push_macro("INCLUDE_ALL_JavaNioFileClosedFileSystemException")
#ifdef RESTRICT_JavaNioFileClosedFileSystemException
#define INCLUDE_ALL_JavaNioFileClosedFileSystemException 0
#else
#define INCLUDE_ALL_JavaNioFileClosedFileSystemException 1
#endif
#undef RESTRICT_JavaNioFileClosedFileSystemException

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (JavaNioFileClosedFileSystemException_) && (INCLUDE_ALL_JavaNioFileClosedFileSystemException || defined(INCLUDE_JavaNioFileClosedFileSystemException))
#define JavaNioFileClosedFileSystemException_

#define RESTRICT_JavaLangIllegalStateException 1
#define INCLUDE_JavaLangIllegalStateException 1
#include <JRE/java/lang/IllegalStateException.h>

@class JavaLangThrowable;

/*!
 @brief Unchecked exception thrown when an attempt is made to invoke an operation on
  a file and the file system is closed.
 */
@interface JavaNioFileClosedFileSystemException : JavaLangIllegalStateException
@property (readonly, class) jlong serialVersionUID NS_SWIFT_NAME(serialVersionUID);

#pragma mark Public

/*!
 @brief Constructs an instance of this class.
 */
- (instancetype __nonnull)init;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)initWithJavaLangThrowable:(JavaLangThrowable *)arg0 NS_UNAVAILABLE;

- (instancetype __nonnull)initWithNSString:(NSString *)arg0 NS_UNAVAILABLE;

- (instancetype __nonnull)initWithNSString:(NSString *)arg0
                     withJavaLangThrowable:(JavaLangThrowable *)arg1 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaNioFileClosedFileSystemException)

inline jlong JavaNioFileClosedFileSystemException_get_serialVersionUID(void);
#define JavaNioFileClosedFileSystemException_serialVersionUID -8158336077256193488LL
J2OBJC_STATIC_FIELD_CONSTANT(JavaNioFileClosedFileSystemException, serialVersionUID, jlong)

FOUNDATION_EXPORT void JavaNioFileClosedFileSystemException_init(JavaNioFileClosedFileSystemException *self);

FOUNDATION_EXPORT JavaNioFileClosedFileSystemException *new_JavaNioFileClosedFileSystemException_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT JavaNioFileClosedFileSystemException *create_JavaNioFileClosedFileSystemException_init(void);

J2OBJC_TYPE_LITERAL_HEADER(JavaNioFileClosedFileSystemException)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_JavaNioFileClosedFileSystemException")
