//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Classes/com/google/j2objc/util/AutoreleasePool.java
//

#include <JRE/J2ObjC_header.h>

#pragma push_macro("INCLUDE_ALL_ComGoogleJ2objcUtilAutoreleasePool")
#ifdef RESTRICT_ComGoogleJ2objcUtilAutoreleasePool
#define INCLUDE_ALL_ComGoogleJ2objcUtilAutoreleasePool 0
#else
#define INCLUDE_ALL_ComGoogleJ2objcUtilAutoreleasePool 1
#endif
#undef RESTRICT_ComGoogleJ2objcUtilAutoreleasePool

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComGoogleJ2objcUtilAutoreleasePool_) && (INCLUDE_ALL_ComGoogleJ2objcUtilAutoreleasePool || defined(INCLUDE_ComGoogleJ2objcUtilAutoreleasePool))
#define ComGoogleJ2objcUtilAutoreleasePool_

@protocol JavaLangRunnable;
@protocol JavaUtilFunctionSupplier;

/*!
 @brief Autorelease pool utilities.
 @author Michał Pociecha-Łoś
 */
@interface ComGoogleJ2objcUtilAutoreleasePool : NSObject

#pragma mark Public

- (instancetype __nonnull)init;

/*!
 @brief Returns the result of the supplier executed inside autorelease pool.
 <p>Temporary objects allocated during execution of the supplier will be deallocated upon
  returning from this method.
 */
+ (id)getWithJavaUtilFunctionSupplier:(id<JavaUtilFunctionSupplier>)supplier;

/*!
 @brief Runs the runnable inside autorelease pool.
 <p>Temporary objects allocated during execution of the runnable will be deallocated upon
  returning from this method.
 */
+ (void)runWithJavaLangRunnable:(id<JavaLangRunnable>)runnable;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleJ2objcUtilAutoreleasePool)

FOUNDATION_EXPORT void ComGoogleJ2objcUtilAutoreleasePool_init(ComGoogleJ2objcUtilAutoreleasePool *self);

FOUNDATION_EXPORT ComGoogleJ2objcUtilAutoreleasePool *new_ComGoogleJ2objcUtilAutoreleasePool_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleJ2objcUtilAutoreleasePool *create_ComGoogleJ2objcUtilAutoreleasePool_init(void);

FOUNDATION_EXPORT void ComGoogleJ2objcUtilAutoreleasePool_runWithJavaLangRunnable_(id<JavaLangRunnable> runnable);

FOUNDATION_EXPORT id ComGoogleJ2objcUtilAutoreleasePool_getWithJavaUtilFunctionSupplier_(id<JavaUtilFunctionSupplier> supplier);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleJ2objcUtilAutoreleasePool)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComGoogleJ2objcUtilAutoreleasePool")
