//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/platform/libcore/ojluni/src/main/java/java/nio/file/attribute/FileAttribute.java
//

#include <JRE/J2ObjC_header.h>

#pragma push_macro("INCLUDE_ALL_JavaNioFileAttributeFileAttribute")
#ifdef RESTRICT_JavaNioFileAttributeFileAttribute
#define INCLUDE_ALL_JavaNioFileAttributeFileAttribute 0
#else
#define INCLUDE_ALL_JavaNioFileAttributeFileAttribute 1
#endif
#undef RESTRICT_JavaNioFileAttributeFileAttribute

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (JavaNioFileAttributeFileAttribute_) && (INCLUDE_ALL_JavaNioFileAttributeFileAttribute || defined(INCLUDE_JavaNioFileAttributeFileAttribute))
#define JavaNioFileAttributeFileAttribute_

/*!
 @brief An object that encapsulates the value of a file attribute that can be set
  atomically when creating a new file or directory by invoking the <code>createFile</code>
  or <code>createDirectory</code>
  methods.
 @since 1.7
 - seealso: PosixFilePermissions#asFileAttribute
 */
@protocol JavaNioFileAttributeFileAttribute < JavaObject >

/*!
 @brief Returns the attribute name.
 @return The attribute name
 */
- (NSString *)name;

/*!
 @brief Returns the attribute value.
 @return The attribute value
 */
- (id)value;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaNioFileAttributeFileAttribute)

J2OBJC_TYPE_LITERAL_HEADER(JavaNioFileAttributeFileAttribute)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_JavaNioFileAttributeFileAttribute")
